2020-09-29 16:55:34,872 - autoReconnect - INFO - 上线成功
2020-09-29 16:56:53,795 - autoReconnect - INFO - 上线成功
2020-09-29 17:02:19,263 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-09-29 17:02:19,594 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 201, in main
    if(not cutScreenShotFitPrgm()):
  File "autoReconnect.py", line 535, in cutScreenShotFitPrgm
    if(pot[0]<0 or pot[1]<0):
TypeError: 'NoneType' object is not subscriptable

2020-09-29 17:02:19,596 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-09-29 17:02:19,599 - autoReconnect - ERROR - 校园客户端程序没有启动, 正在尝试重启客户端
2020-09-29 17:02:23,346 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-09-29 17:02:24,270 - autoReconnect - WARNING - 当前截图不属于客户端,正在将客户端调前... 精度:0.9984571933746338
2020-09-29 17:02:25,631 - autoReconnect - WARNING - 当前截图不属于客户端,正在将客户端调前... 精度:0.9984568357467651
2020-09-29 17:02:27,251 - autoReconnect - WARNING - 当前截图不属于客户端,正在将客户端调前... 精度:0.9984570145606995
2020-09-29 17:02:28,524 - autoReconnect - WARNING - 当前截图不属于客户端,正在将客户端调前... 精度:0.9984570145606995
2020-09-29 17:02:29,818 - autoReconnect - WARNING - 当前截图不属于客户端,正在将客户端调前... 精度:0.998457133769989
2020-09-29 17:02:31,130 - autoReconnect - WARNING - 当前截图不属于客户端,正在将客户端调前... 精度:0.998457133769989
2020-09-29 17:02:32,487 - autoReconnect - WARNING - 当前截图不属于客户端,正在将客户端调前... 精度:0.998457133769989
2020-09-29 17:02:33,828 - autoReconnect - WARNING - 当前截图不属于客户端,正在将客户端调前... 精度:0.9984569549560547
2020-09-29 17:02:35,132 - autoReconnect - WARNING - 当前截图不属于客户端,正在将客户端调前... 精度:0.9984570145606995
2020-09-29 17:02:36,598 - autoReconnect - WARNING - 当前截图不属于客户端,正在将客户端调前... 精度:0.9984568357467651
2020-09-29 17:02:39,372 - autoReconnect - INFO - 即将操作客户端即将登陆
2020-09-29 17:02:39,454 - autoReconnect - INFO - 找到登录连接按钮
2020-09-29 17:02:39,512 - autoReconnect - INFO - 鼠标双击成功,pot176,321
2020-09-29 17:02:43,174 - autoReconnect - INFO - 点击登录按钮成功
2020-09-29 17:02:44,194 - autoReconnect - INFO - 上线成功
2020-09-29 17:03:19,930 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-09-29 17:03:20,285 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-09-29 17:03:21,186 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-09-29 17:03:21,255 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-09-29 17:03:37,511 - autoReconnect - WARNING - 网络连接不通,累计:0
2020-09-29 17:03:37,521 - autoReconnect - INFO - 发现自助排障工具窗口, 窗口句柄:199792
2020-09-29 17:03:37,571 - autoReconnect - INFO - 已经向排障工具发送结束进程指令 True
2020-09-29 17:03:38,572 - autoReconnect - INFO - Stop fixTools Success
2020-09-29 17:03:40,869 - autoReconnect - INFO - 客户端遇到错误,即将重试
2020-09-29 17:03:40,994 - autoReconnect - INFO - 找到重试按钮
2020-09-29 17:03:41,062 - autoReconnect - INFO - 鼠标双击成功,pot79,408
2020-09-29 17:03:43,605 - autoReconnect - INFO - 点击重试成功
2020-09-29 17:03:58,362 - autoReconnect - INFO - 客户端遇到错误,即将重试
2020-09-29 17:03:58,623 - autoReconnect - INFO - 找到重试按钮
2020-09-29 17:03:58,779 - autoReconnect - INFO - 鼠标双击成功,pot79,408
2020-09-29 17:04:02,338 - autoReconnect - INFO - 点击重试成功
2020-09-29 17:04:43,980 - autoReconnect - INFO - 即将操作客户端即将登陆
2020-09-29 17:04:44,053 - autoReconnect - INFO - 找到登录连接按钮
2020-09-29 17:04:44,108 - autoReconnect - INFO - 鼠标双击成功,pot176,321
2020-09-29 17:05:04,375 - autoReconnect - INFO - 即将操作客户端即将登陆
2020-09-29 17:05:04,447 - autoReconnect - ERROR - 找不到登录按钮,精度:0.9947039484977722 正在重试
2020-09-29 17:05:05,269 - autoReconnect - INFO - 即将操作客户端即将登陆
2020-09-29 17:05:05,338 - autoReconnect - ERROR - 找不到登录按钮,精度:0.9947039484977722 正在重试
2020-09-29 17:05:06,147 - autoReconnect - INFO - 即将操作客户端即将登陆
2020-09-29 17:05:06,230 - autoReconnect - ERROR - 找不到登录按钮,精度:0.9947150945663452 正在重试
2020-09-29 17:05:07,022 - autoReconnect - INFO - 即将操作客户端即将登陆
2020-09-29 17:05:07,104 - autoReconnect - ERROR - 找不到登录按钮,精度:0.9947039484977722 正在重试
2020-09-29 17:05:07,920 - autoReconnect - INFO - 即将操作客户端即将登陆
2020-09-29 17:05:07,990 - autoReconnect - ERROR - 找不到登录按钮,精度:0.9956763386726379 正在重试
2020-09-29 17:05:08,822 - autoReconnect - INFO - 即将操作客户端即将登陆
2020-09-29 17:05:08,902 - autoReconnect - ERROR - 找不到登录按钮,精度:0.9947039484977722 正在重试
2020-09-29 17:05:09,687 - autoReconnect - INFO - 即将操作客户端即将登陆
2020-09-29 17:05:09,759 - autoReconnect - ERROR - 找不到登录按钮,精度:0.9967365264892578 正在重试
2020-09-29 17:05:10,538 - autoReconnect - INFO - 即将操作客户端即将登陆
2020-09-29 17:05:10,615 - autoReconnect - ERROR - 找不到登录按钮,精度:0.994704008102417 正在重试
2020-09-29 17:05:11,445 - autoReconnect - INFO - 即将操作客户端即将登陆
2020-09-29 17:05:11,525 - autoReconnect - ERROR - 找不到登录按钮,精度:0.994704008102417 正在重试
2020-09-29 17:05:12,336 - autoReconnect - INFO - 即将操作客户端即将登陆
2020-09-29 17:05:12,406 - autoReconnect - ERROR - 找不到登录按钮,精度:0.9947039484977722 正在重试
2020-09-29 17:05:13,176 - autoReconnect - INFO - 即将操作客户端即将登陆
2020-09-29 17:05:13,259 - autoReconnect - ERROR - 找不到登录按钮,精度:0.9947039484977722 正在重试
2020-09-29 17:05:14,049 - autoReconnect - INFO - 即将操作客户端即将登陆
2020-09-29 17:05:14,127 - autoReconnect - ERROR - 找不到登录按钮,精度:0.9947150945663452 正在重试
2020-09-29 17:05:14,950 - autoReconnect - INFO - 即将操作客户端即将登陆
2020-09-29 17:05:15,028 - autoReconnect - ERROR - 找不到登录按钮,精度:0.9947039484977722 正在重试
2020-09-29 17:05:15,848 - autoReconnect - INFO - 即将操作客户端即将登陆
2020-09-29 17:05:15,937 - autoReconnect - ERROR - 找不到登录按钮,精度:0.9956763386726379 正在重试
2020-09-29 17:05:16,853 - autoReconnect - INFO - 即将操作客户端即将登陆
2020-09-29 17:05:16,929 - autoReconnect - ERROR - 找不到登录按钮,精度:0.9947039484977722 正在重试
2020-09-29 17:05:17,943 - autoReconnect - INFO - 点击登录按钮成功
2020-09-29 17:05:20,020 - autoReconnect - INFO - 上线成功
2020-09-29 19:43:27,066 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-09-29 19:43:27,225 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-09-29 19:43:28,272 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-09-29 19:43:28,275 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-09-29 20:14:52,349 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-09-29 20:14:52,521 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-09-29 20:14:53,307 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-09-29 20:14:53,308 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-09-29 21:13:51,193 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-09-29 21:13:51,359 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-09-29 21:13:52,143 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-09-29 21:13:52,144 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-09-29 21:43:39,012 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-09-29 21:43:39,179 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-09-29 21:43:39,961 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-09-29 21:43:39,962 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-09-29 21:53:22,763 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-09-29 21:53:22,933 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-09-29 21:53:23,725 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-09-29 21:53:23,726 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-09-29 22:04:01,385 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-09-29 22:04:01,545 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-09-29 22:04:02,337 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-09-29 22:04:02,337 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-09-29 22:21:16,422 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-09-29 22:21:16,593 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-09-29 22:21:17,373 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-09-29 22:21:17,374 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-09-29 22:22:22,781 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-09-29 22:22:22,948 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-09-29 22:22:23,738 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-09-29 22:22:23,739 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-09-30 01:17:37,961 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-09-30 01:17:49,033 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-09-30 01:17:49,206 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-09-30 01:17:50,011 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-09-30 01:17:50,011 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-09-30 01:17:53,017 - autoReconnect - INFO - 即将操作客户端即将登陆
2020-09-30 01:17:53,080 - autoReconnect - INFO - 找到登录连接按钮
2020-09-30 01:17:53,142 - autoReconnect - INFO - 鼠标双击成功,pot176,321
2020-09-30 01:17:55,750 - autoReconnect - INFO - 点击登录按钮成功
2020-09-30 01:17:56,378 - autoReconnect - INFO - 上线成功
2020-09-30 05:29:17,875 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-09-30 05:29:18,063 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-09-30 05:29:18,850 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-09-30 05:29:18,850 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-09-30 05:29:24,145 - autoReconnect - WARNING - 网络连接不通,累计:0
2020-09-30 05:29:34,750 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-09-30 05:29:34,922 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-09-30 05:29:35,732 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-09-30 05:29:35,732 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-09-30 05:30:31,845 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-09-30 05:30:32,016 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-09-30 05:30:32,832 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-09-30 05:30:32,832 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-09-30 05:30:38,065 - autoReconnect - WARNING - 网络连接不通,累计:0
2020-09-30 05:30:43,330 - autoReconnect - WARNING - 网络连接不通,累计:1
2020-09-30 05:31:00,970 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-09-30 05:31:01,142 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-09-30 05:31:01,936 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-09-30 05:31:01,936 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-09-30 05:32:08,169 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-09-30 05:32:08,341 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-09-30 05:32:09,143 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-09-30 05:32:09,143 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-09-30 05:32:29,847 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-09-30 05:32:30,034 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-09-30 05:32:30,823 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-09-30 05:32:30,823 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-09-30 05:33:51,046 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-09-30 05:33:51,218 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-09-30 05:33:52,013 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-09-30 05:33:52,013 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-09-30 05:33:57,261 - autoReconnect - WARNING - 网络连接不通,累计:0
2020-09-30 11:12:44,452 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-09-30 11:12:44,650 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-09-30 11:12:45,588 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-09-30 11:12:45,596 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-09-30 11:13:25,172 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-09-30 11:13:25,364 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-09-30 11:13:26,188 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-09-30 11:13:26,191 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-09-30 11:13:31,583 - autoReconnect - WARNING - 网络连接不通,累计:0
2020-09-30 11:19:52,796 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-09-30 11:19:52,990 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-09-30 11:19:53,829 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-09-30 11:19:53,829 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-09-30 11:21:12,028 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-09-30 11:21:12,255 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-09-30 11:21:13,141 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-09-30 11:21:13,141 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-09-30 11:25:24,613 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-09-30 11:25:24,840 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-09-30 11:25:25,755 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-09-30 11:25:25,756 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-09-30 11:32:23,670 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-09-30 11:32:23,871 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-09-30 11:32:24,755 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-09-30 11:32:24,756 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-09-30 11:33:50,175 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-09-30 11:33:50,385 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-09-30 11:33:51,428 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-09-30 11:33:51,431 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-09-30 11:33:52,221 - autoReconnect - WARNING - 当前截图不属于客户端,正在将客户端调前... 精度:0.9960744380950928
2020-09-30 11:41:05,678 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-09-30 11:41:05,763 - autoReconnect - WARNING - 当前截图不属于客户端,正在将客户端调前... 精度:0.9960745573043823
