2020-10-09 00:57:27,612 - autoReconnect - INFO - 找不到客户端窗口,正在尝试打开客户端...
2020-10-09 00:57:39,105 - autoReconnect - WARNING - 当前截图不属于客户端,正在将客户端调前... 精度:0.9984567165374756
2020-10-09 00:57:40,135 - autoReconnect - WARNING - 当前截图不属于客户端,正在将客户端调前... 精度:0.9984567165374756
2020-10-09 00:57:41,071 - autoReconnect - WARNING - 当前截图不属于客户端,正在将客户端调前... 精度:0.9984565377235413
2020-10-09 00:57:42,008 - autoReconnect - WARNING - 当前截图不属于客户端,正在将客户端调前... 精度:0.9984567165374756
2020-10-09 00:57:42,944 - autoReconnect - WARNING - 当前截图不属于客户端,正在将客户端调前... 精度:0.9984567165374756
2020-10-09 00:57:43,880 - autoReconnect - WARNING - 当前截图不属于客户端,正在将客户端调前... 精度:0.9984567165374756
2020-10-09 00:57:44,832 - autoReconnect - WARNING - 当前截图不属于客户端,正在将客户端调前... 精度:0.998456597328186
2020-10-09 00:57:45,800 - autoReconnect - WARNING - 当前截图不属于客户端,正在将客户端调前... 精度:0.9984567165374756
2020-10-09 00:57:46,751 - autoReconnect - WARNING - 当前截图不属于客户端,正在将客户端调前... 精度:0.9984567165374756
2020-10-09 00:57:47,703 - autoReconnect - WARNING - 当前截图不属于客户端,正在将客户端调前... 精度:0.9984565377235413
2020-10-09 00:57:49,872 - autoReconnect - INFO - 即将操作客户端即将登陆
2020-10-09 00:57:49,966 - autoReconnect - INFO - 找到登录连接按钮
2020-10-09 00:57:50,028 - autoReconnect - INFO - 鼠标双击成功,pot176,321
2020-10-09 00:57:53,101 - autoReconnect - INFO - 点击登录按钮成功
2020-10-09 00:57:53,664 - autoReconnect - INFO - 上线成功
2020-10-09 00:59:47,603 - autoReconnect - INFO - 发现自助排障工具窗口, 窗口句柄:67090
2020-10-09 00:59:47,605 - autoReconnect - INFO - 已经向排障工具发送结束进程指令 True
2020-10-09 00:59:48,605 - autoReconnect - INFO - Stop fixTools Success
2020-10-09 00:59:48,740 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-09 00:59:49,346 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-09 00:59:49,347 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-09 00:59:58,119 - autoReconnect - INFO - 即将操作客户端即将登陆
2020-10-09 00:59:58,191 - autoReconnect - INFO - 找到登录连接按钮
2020-10-09 00:59:58,243 - autoReconnect - INFO - 鼠标双击成功,pot176,321
2020-10-09 01:00:04,791 - autoReconnect - INFO - 点击登录按钮成功
2020-10-09 01:00:05,401 - autoReconnect - INFO - 上线成功
2020-10-09 01:00:11,171 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-10-09 01:00:11,302 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-09 01:00:11,822 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-09 01:00:11,823 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-09 01:00:15,893 - autoReconnect - INFO - 即将操作客户端即将登陆
2020-10-09 01:00:15,945 - autoReconnect - INFO - 找到登录连接按钮
2020-10-09 01:00:15,997 - autoReconnect - INFO - 鼠标双击成功,pot176,321
2020-10-09 01:00:21,533 - autoReconnect - INFO - 点击登录按钮成功
2020-10-09 01:00:22,123 - autoReconnect - INFO - 上线成功
2020-10-09 09:00:52,486 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-10-09 09:00:52,611 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-09 09:00:53,128 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-09 09:00:53,129 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-09 11:02:36,906 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-10-09 11:02:37,036 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-09 11:02:37,555 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-09 11:02:37,556 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-09 12:31:52,587 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-10-09 12:31:52,708 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-09 12:31:53,244 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-09 12:31:53,244 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-09 13:25:32,326 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-10-09 13:25:32,439 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-09 13:25:32,959 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-09 13:25:32,960 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-09 13:27:57,108 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-10-09 13:27:57,240 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-09 13:27:57,759 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-09 13:27:57,760 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-09 15:12:20,342 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-10-09 15:12:20,477 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-09 15:12:21,007 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-09 15:12:21,008 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-09 17:56:11,884 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-10-09 17:56:12,020 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-09 17:56:12,547 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-09 17:56:12,548 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-09 22:00:57,413 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-10-09 22:00:57,539 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-09 22:00:58,062 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-09 22:00:58,063 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-09 22:39:41,647 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-10-09 22:39:41,979 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-09 22:39:42,528 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-09 22:39:42,528 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-10 00:25:48,766 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-10-10 00:25:48,892 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-10 00:25:49,423 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-10 00:25:49,423 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-10 07:56:32,050 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-10-10 07:56:32,190 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-10 07:56:32,736 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-10 07:56:32,736 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-10 09:41:35,864 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-10-10 09:41:35,989 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-10 09:41:36,520 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-10 09:41:36,520 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-10 09:45:32,159 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-10-10 09:45:32,315 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-10 09:45:32,831 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-10 09:45:32,831 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-10 12:31:50,676 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-10-10 12:31:50,927 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-10 12:31:51,473 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-10 12:31:51,473 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-10 13:06:19,110 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-10-10 13:06:19,235 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-10 13:06:19,765 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-10 13:06:19,765 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-10 13:34:32,144 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-10-10 13:34:32,268 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-10 13:34:32,784 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-10 13:34:32,784 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-10 15:49:10,046 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-10-10 15:49:10,171 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-10 15:49:10,702 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-10 15:49:10,702 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-10 16:31:26,683 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-10-10 16:31:26,809 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-10 16:31:27,339 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-10 16:31:27,339 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-10 17:44:39,061 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-10-10 17:44:39,186 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-10 17:44:39,716 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-10 17:44:39,716 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-10 18:17:54,491 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-10-10 18:17:54,631 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-10 18:17:55,147 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-10 18:17:55,147 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
